CREATE TABLE ADDRESS(
    ID NUMBER(10,0) NOT NULL ENABLE,
    STREET_NAME VARCHAR2(40),
    CITY_NAME VARCHAR2(40),
    STATE_NAME VARCHAR2(40),
    ZIP_CODE VARCHAR2(40),
    CONSTRAINT ADDRESS_PK PRIMARY KEY (ID)    
);

CREATE SEQUENCE  address_id_sequence;
