CREATE TABLE CERTIFICATE(
    ID NUMBER(10,0) NOT NULL ENABLE,
    CERTIFICATE_NAME VARCHAR2(30),
    EMPLOYEE_ID NUMBER(10,0),
    CONSTRAINT CERTIFICATE_PK PRIMARY KEY (ID)   
);

CREATE SEQUENCE  certificate_id_sequence;
