CREATE TABLE EMPLOYEE (
   ID NUMBER(10,0) NOT NULL ENABLE,
   FIRST_NAME VARCHAR2(20),
   LAST_NAME  VARCHAR(20),
   SALARY FLOAT(126),
   ADDRESS NUMBER(10,0) NOT NULL ENABLE,
   CONSTRAINT EMPLOYEE_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE employee_sequence;


 
